version: "3"

services:
  postgres:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_DB: postgres_connection_creator
      POSTGRES_USER: postgres_connection_creator
      POSTGRES_PASSWORD: postgres_connection_creator
    volumes:
      - ./postgres_connection_creator-data:/var/lib/postgresql/data
    network_mode: host
    expose:
      - 5432
#    ports:
#      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres_connection_creator" ]
      interval: 5s
      retries: 5
  
  app:
    restart: always
    build: .
    environment:
      CONFIG_PATH: src/config/example/config.json
    network_mode: host
    expose:
      - 8000
#    ports:
#      - 8000:8000
    depends_on:
      - postgres
    entrypoint: /bin/bash /code/src/entrypoint.sh

volumes:
  postgres-db-volume:
    driver: local