db_connection:
  type: none  # none postgres
  settings:
    db_user: postgres
    db_password: postgres
    db_name: postgres
    db_port: 5432
    db_host: 127.0.0.1

services:
  user:
#    settings:
#      repository:
#        type: in_memory  # in_memory db_connection_creator postgres
#        settings:
    repository:
      type: in_memory  # in_memory db_connection_creator postgres
      settings: