plugins:
  postgres_connection_creator:
    db_user: postgres
    db_password: postgres
    db_name: postgres
    db_port: 5432
    db_host: 127.0.0.1


  user:
    repository:
      type: postgres
      settings: